### ISSUE TITLE
Unable to install Addin

### ISSUE THREAD

**Issue by BLMoran** [ironwest/gtsummary_addin#14]
I've tried to install the add-in, but get the following error message:

> devtools::install_github("ironwest/gtsummary_addin")
Downloading GitHub repo ironwest/gtsummary_addin@HEAD
√  checking for file 'C:\Users\benja\AppData\Local\Temp\RtmpKIDiLF\remotes1a844f7212b7\ironwest-gtsummary_addin-bc7b404/DESCRIPTION' (1.1s)
-  preparing 'gtsummaryAddin': (868ms)
√  checking DESCRIPTION meta-information ... 
   Warning: C:/Users/benja/AppData/Local/Temp/RtmpKIlaX1/Rbuild147c529b1319/gtsummaryAddin/man/add_p_tbl_summary_test.Rd:6: unexpected section header '\usage'
   Warning: C:/Users/benja/AppData/Local/Temp/RtmpKIlaX1/Rbuild147c529b1319/gtsummaryAddin/man/add_p_tbl_summary_test.Rd:9: unexpected section header '\value'
   Warning: C:/Users/benja/AppData/Local/Temp/RtmpKIlaX1/Rbuild147c529b1319/gtsummaryAddin/man/add_p_tbl_summary_test.Rd:12: unexpected section header '\description'
   Warning: C:/Users/benja/AppData/Local/Temp/RtmpKIlaX1/Rbuild147c529b1319/gtsummaryAddin/man/add_p_tbl_summary_test.Rd:15: unexpected END_OF_INPUT '
   '
-  checking for LF line-endings in source and make files and shell scripts (414ms)
-  checking for empty or unneeded directories
-  building 'gtsummaryAddin_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/benja/OneDrive/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'gtsummaryAddin' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: replacing previous import 'gtsummary::as_flextable' by 'flextable::as_flextable' when loading 'gtsummaryAddin'
** help
Error : (converted from warning) C:/Users/benja/AppData/Local/Temp/Rtmpojo6Dn/R.INSTALL2e946ad67bb3/gtsummaryAddin/man/add_p_tbl_summary_test.Rd:6: unexpected section header '\usage'
ERROR: installing Rd objects failed for package 'gtsummaryAddin'
* removing 'C:/Users/benja/OneDrive/Documents/R/win-library/4.0/gtsummaryAddin'
Error: Failed to install 'gtsummaryAddin' from GitHub:
  (converted from warning) installation of package ‘C:/Users/benja/AppData/Local/Temp/RtmpKIDiLF/file1a84faf54ec/gtsummaryAddin_0.0.0.9000.tar.gz’ had non-zero exit status

Any idea what's going on?

Thanks,

Ben

**Comment by ironwest** [comment]
Hi @BLMoran 
Apology for the slow response. 
The error you reported due to bad documentation. I corrected the documentation so, the package should be able to install now.

**Comment by BLMoran** [comment]
Thanks for that.
When I try to open the addin, I get this error message.

> trial <- trial
> gtsummaryAddin:::tbl_summary_addin()
Error in use_bs_popover() : could not find function "use_bs_popover"

The addin works when I load the bsplus library, but should this not work without having to load it?

Thanks,

Ben

**Comment by ironwest** [comment]
@BLMoran 
Thanks for the recommendation. I forgot to update the NAMESPACE file. Now, the package should automatically be loaded.
