### ISSUE TITLE
Limit column numbers to load.

### ISSUE THREAD

**Issue by ironwest** [ironwest/gtsummary_addin#9]
Suggestion from @larmarange :

> when loading, by default all variables are selected. If the data.frame has a lot of variables, it could be a problem because the initial table will be very long to display. Maybe, it could be wise to test the number of columns in the data.frame and to unselect all variables if this number is high

**Comment by ironwest** [comment]
TODO:
 -> Check column number for data.frame and load up to 5 columns at the beginning.

**Comment by ironwest** [comment]
@larmarange
It took a long time but added functionality for loading up to 5 columns at the beginning of app load.

**Comment by larmarange** [comment]
Thanks

Joseph Larmarange
